Marwa-exercises- week1
HackYourHomework/JavaScript1 pull request #14
Opened 2020-11-09 22:32 UTC by Marwa-kwara

2020-11-14 20:08 UTC, jasperkennis requested changes
Hi Marwa! 

Nice work with the homework! There are a few concepts I think would be good to check a bit more, please see my comments. Let me know if you have any questions!

Enjoy the weekend!

2020-11-14 20:08 UTC, jasperkennis commented on Week1/Homework/exercise6.js
> +myFavoriteAnimals.onMoreAnimal=["piglet"];
I think you are mixing **objects** and **arrays** here. Note that the outcome of your script is this:

```
I think arry is empty and the out put of it is undefind
[]
object
[ 'cats', { favoritePets: 'rabbits', iLoveDogs: 'false' } ]
[ 'piglet' ]
```

Insteed of `myFavoriteAnimals.onMoreAnimal=["piglet"];`, try using `myFavoriteAnimals.push('piglet')` and see how the result is different.

In the end, we should first console.log 4 animals, and then 5.

2020-11-14 20:08 UTC, jasperkennis commented on Week1/Homework/exercise9.js
> +let x=7;
I can see that the values of your variables are correct. But let's practise something else: for completeness sake, try to assign `x = x % 3`, and then console.log the **new** value of x.

2020-11-14 20:08 UTC, jasperkennis commented on Week1/Homework/exercise10.js
> +console.log('Two different sizes');
The first part here is correct, but the if statement isn't entirely complete yet. Please see if you can find a good example of an if statement. If you get stuck on this, just let me know and we can look at it together.

2020-11-17 12:49 UTC, Marwa-kwara commented on Week1/Homework/exercise6.js
> +console.log(zooAnimals);
okay !

2020-11-17 21:14 UTC, Marwa-kwara commented
Hi @jasperkennis,
Thank you for reviewing my homework,I did some changes on exercises 6/9/10, can you please check it again?
Thanks in advance,

2020-11-17 21:16 UTC, Marwa-kwara commented
some changes on the exercises 6,9,10

2020-11-17 21:16 UTC, closed without merging

2020-11-18 11:31 UTC, jasperkennis commented on Week1/Homework/exercise10.js
> +console.log('Two different sizes');
Hi Marwa! Nice work with the updates. There's one important thing left, about this if statement.

You have this: 
```js
if (seasons.length > monthes.length);
console.log('Two different sizes');
```

Actually, the if statement should be something like this:
```js
if (seasons.length > monthes.length) {
  console.log('Two different sizes');
} else {
  console.log('The same sizes');
}
```

Notice the curly brackets that indicate the block of logic that happens _if_ the condition is met.

2020-11-19 21:16 UTC, Marwa-kwara commented on Week1/Homework/exercise10.js
> +console.log('Two different sizes');
Oh yes, I forgot to add the curly brackets,
Thank you ,

2020-11-21 13:18 UTC, jasperkennis commented on Week1/Homework/exercise10.js
> +console.log('Two different sizes');
I think you might not have pushed the changes, but I can see from your homework for week2 that this is now clear to you:)