EHAB HW Week 2 Attatched 5 files
HackYourHomework/JavaScript1 pull request #24
Opened 2020-11-17 14:07 UTC by ehabwasel

2020-11-17 14:07 UTC, ehabwasel commented
My js  HW week 2

2020-11-21 13:13 UTC, jasperkennis requested changes
Hi Ehab,

Nice work! For EX3 a little additional change work is required, please take a look. I also added a tip to EX5, that you might find helpful in the future.

Have a great weekend! Jasper

2020-11-21 13:13 UTC, jasperkennis commented on Week2/EX3.JS
> +console.log(myrecipe);
While this will log the object, you haven't used a loop.

The assignment asks to `Log each property out separately, using a loop (for, while or do/while)`. Can you give that a try?

2020-11-21 13:13 UTC, jasperkennis commented on Week2/EX5.JS
> +     console.log("You already read " + '"' +Books[i].title +'"')
Nice work! I have a suggestion for you. There is an alternative syntax that makes working with strings a little easier. Here is an example:
```js
console.log(`You already read "${Books[i].title}".`)
```

In Javascript, we can place a string in between this symbol (**`**), and add variables in it by wrapping them with **${}**. In some cases this can be easier then using several plusses.

2020-11-21 21:45 UTC, ehabwasel commented on Week2/EX5.JS
> +     console.log("You already read " + '"' +Books[i].title +'"')
thanks for useful feedback

2020-11-21 22:43 UTC, ehabwasel commented on Week2/EX3.JS
> +console.log(myrecipe);
THANKS FOR YOUR HELP ........but actually I don,t understand why do we need to use a loop for this exercise it does not make any scene to loop through only one object

2020-11-29 12:06 UTC, jasperkennis requested changes
Hi Ehab, sorry for the late reply, I missed your question somehow. I added a bit of an example, hope this helps.

2020-11-29 12:06 UTC, jasperkennis commented on Week2/EX3.JS
> +console.log(myrecipe);
I think you have understood the concept of using a loop for iterating over an array very well. Like you say, we have a single object here. But, your **one object** has **multiple keys**; "meal", "serves" and "ingredients". The goal of the exercise is to iterate over these keys.

There are several ways to iterate over the keys of an object. Here are two examples:

```js
var myrecipe = {
  Meal: 'Omelette',
  Serves: 2,
  Ingredients: ["4 eggs","2 strips of bacon","1 tsp salt/pepper"]
};

/**
 * Using a "for in" loop
 */
for (const key in myrecipe) {
  if (myrecipe.hasOwnProperty(key)) {
    const element = myrecipe[key];
    console.log(key)
    console.log(element)
  }
}

/**
 * Using Object.keys and a regular for loop
 */
const myKeys = Object.keys(myrecipe)

for (let i = 0; i < myKeys.length; i++) {
  const key = myKeys[i];
  console.log(key)
  console.log(myrecipe[key])
}
 ```

2020-12-16 21:30 UTC, ehabwasel commented on Week2/EX3.JS
> +console.log(myrecipe);
thanks for useful feedback

2021-04-06 04:00 UTC, closed without merging