Ehab HW Week3 5EX files + credit project
HackYourHomework/JavaScript1 pull request #29
Opened 2020-11-21 22:37 UTC by ehabwasel

..

2020-11-21 22:38 UTC, ehabwasel commented
.

2020-11-26 17:56 UTC, jasperkennis requested changes
Hi Ehab,

Nice work on this, there's a lot of concept coming together in these exercises. I'm particularly impressed with your work on the Credit.js!

Please take an look at my comments, in particular on exersise 1 and 2, there are a few important concepts I think you will want to work a bit more on.

Good luck! Jasper

2020-11-26 17:56 UTC, jasperkennis commented on Week3/Credit.js
> +  validate1= false;}
Since you already set your variables to `false`, you can skip setting them to `false` again. This will make your code a bit shorter.

2020-11-26 17:56 UTC, jasperkennis commented on Week3/Credit.js
> + }}
I can see you applied a lot of what you learned here, nice work! As a general tip, try to keep your code a little more clean. For example the bit above, you can format a bit more to look like this:

```js
// this condition for the type of inpute is only numbers of inpute
for (let i=0;i<inputtxt.length;i++) {
  if (!((inputtxt.charCodeAt([i])>=48 && inputtxt.charCodeAt([i])<=57)))
  { 
    console.log("Invalid! The input ", inputtxt, " should contain only numbers!");
    validate2 = false;
    break; 
  }
  else {
    validate2= true;
  }
}
```
Which is exactly the same, but with a little more newlines and spacing. When you work in a professional environment, there is often a standard formatting that everyone in the company is required to follow. To check the code style, we use a "linter". If you install a linter on your code editor, it will often automatically format much of the code for you! It's very helpful, not in the least because well formatted code is easy to read and will prevent bugs.

To be clear, there is nothing wrong with your code at all, it works exactly as it should!

2020-11-26 17:56 UTC, jasperkennis commented on Week3/EX1.JS
> +let ehab;
You can skip the initiation of the variable here, because when you create a function that accepts an argument, javascript will initiate the variable for you when it is called.

2020-11-26 17:56 UTC, jasperkennis commented on Week3/EX1.JS
> +   return  console.log("You Are" ,rand, "Ehab!")
Try to replace `"Ehab!"` here with the value you received from the function argument.

2020-11-26 17:56 UTC, jasperkennis commented on Week3/EX1.JS
> +giveCompliment(ehab)
Try to pass a _string_ instead of a _variable_.

2020-11-26 17:56 UTC, jasperkennis commented on Week3/EX2.JS
> +  dogAge= humanAge*7;
Instead of passing dogAge as an argument to your function, try to define it on this line, like this:

```js
const dogAge= humanAge*7;
```

2020-11-26 17:56 UTC, jasperkennis commented on Week3/EX3.JS
> +    `working as a ${randomValueOf(jobs)}`
Nice work with this concatenation, looks good.

2020-11-26 17:56 UTC, jasperkennis commented on Week3/EX5.js
> +calculateTotalPrice("")
When you have a function that takes no arguments, you can also call it without any arguments, like so:

```js
calculateTotalPrice("")
```

2020-11-26 20:15 UTC, ehabwasel commented on Week3/EX3.JS
> +    `working as a ${randomValueOf(jobs)}`
THANKS

2020-11-26 20:15 UTC, ehabwasel commented on Week3/EX2.JS
> +  dogAge= humanAge*7;
I didi it thanks

2020-11-26 20:17 UTC, ehabwasel commented on Week3/EX1.JS
> +giveCompliment(ehab)
I did it THANKS

2020-11-26 20:23 UTC, ehabwasel commented on Week3/Credit.js
> + }}
OK I FIXED IT THANKS

2020-11-26 20:25 UTC, ehabwasel commented on Week3/Credit.js
> +  validate1= false;}
THANKS for these valuable advises

2020-11-29 12:19 UTC, jasperkennis requested changes
Hi Ehab! Great work with all the improvements! I left one important comment on EX1.js. The thing is, when I look at the other exercises I think you already understood the concepts that are relevant here, but looking at EX1 it would seem like there is a bit of work to do still.

Please take a good look and make sure it all makes sense to you. Having the perfect answer is not so important, but it ís very important that you really understand these concepts, they are fundamental to your future career as a developer.

If any unclarity remains, please let me know, then we can schedule a quick call about it.

Have a great Sunday! J

2020-11-29 12:19 UTC, jasperkennis commented on Week3/EX1.JS
> +giveCompliment()
I think a few concepts are getting mixed up here. I made a little example based on what you already had. Instead of calling `giveCompliment` once, I call it three times, passing a different name every time. Note how I changed the parameter of your function to `name`, and the also pass that to the console log.

```js
function giveCompliment(name) {
  const compliments=["great","awaiswm","good","verygood","exellent","smart ","strong","courageous","sunshine ","Goodlooking","INTELGENT"];
  let rand= compliments[Math.random() * compliments.length | 0];

  // Note how the parameter "name" is passed here:
  return console.log(name, "! You Are" ,rand)
}

giveCompliment('ehab')
giveCompliment('jasper')
giveCompliment('fedde')
```

2020-12-16 19:13 UTC, ehabwasel commented on Week3/EX1.JS
> +giveCompliment()
thanks a lot i figure out it

2021-04-06 04:01 UTC, closed without merging